### PR TITLE
DataInputSchema can only be a string and not an object

### LINKED ISSUE #194: DataInputSchema can only be a string and not an object
**What happened**:
Trying to parse workflow definition with dataInputSchema defined as an object fails.

``` json
{
   "id": "greeting",
   "version": "1.0.0",
   "specVersion": "0.8",
   "name": "Greeting Workflow",
   "description": "Greet Someone",
   "start": "Greet",
   "dataInputSchema": {
      "schema": {
         "title": "Hello World Schema",
         "properties": {
            "person": {
               "type": "object",
               "properties": {
                  "name": {
                     "type": "string"
                  }
               },
               "required": [
                  "name"
               ]
            }
         },
         "required": [
            "person"
         ]
      }
   },
   "functions": [
      {
         "name": "greetingFunction",
         "operation": "file://myapis/greetingapis.json#greeting"
      }
   ],
   "states": [
      {
         "name": "Greet",
         "type": "operation",
         "actions": [
            {
               "functionRef": {
                  "refName": "greetingFunction",
                  "arguments": {
                     "name": "${ .person.name }"
                  }
               },
               "actionDataFilter": {
                  "results": "${ {greeting: .greeting} }"
               }
            }
         ],
         "end": true
      }
   ]
}
```

The above dataInputSchema is not accepted because in the [code](https://github.com/serverlessworkflow/sdk-go/blob/d19b014b0dcb2dbc27e53edebe713d7100d9cba7/model/workflow.go#L506) - this is only accepting a string.

**What you expected to happen**:
As per the spec, the dataInputSchema can be a string or an object.  Both should be accepted

**How to reproduce it**:
Parse the above Workflow definition using sdk-go

**Anything else we need to know?**:

**Environment**:

- Go version: go version go1.20.3 darwin/arm64

### PR DESCRIPTION
**Pull request by spolti**
fixes #194

**Many thanks for submitting your Pull Request :heart:!**

**What this PR does / why we need it**:

**Special notes for reviewers**:

**Additional information (if needed):**

### CODE REVIEW

**Comment by spolti** [comment]
@ricardozanini PTAL.

there is one test specific that I left I comment, we would need to revisit that later.

File: model/workflow.go [hunk 1]
```diff
@@ -505,7 +507,7 @@ type StateDataFilter struct {
 // DataInputSchema Used to validate the workflow data input against a defined JSON Schema
 type DataInputSchema struct {
 	// +kubebuilder:validation:Required
-	Schema string `json:"schema" validate:"required"`
+	Schema Object `json:"schema" validate:"required"`
```
[the remark this answers is not in the document]
Comment (spolti) [reply model/workflow.go:510]: I didn't find on the Spec if the Schema is required or not.
If it is not mandatory, then +1 to have it as pointer.

[the remark this answers is not in the document]
Comment (ricardozanini) [reply model/workflow.go:510]: Go ahead with pointer :)

File: model/workflow_validator_test.go [hunk 2]
```diff
@@ -425,26 +425,28 @@ func TestDataInputSchemaStructLevelValidation(t *testing.T) {
...
 	buildFunctionRef(baseWorkflow, action1, "function 1")
 
+	sampleSchema := FromString("sample schema")
+
 	testCases := []ValidationCase{
 		// TODO Empty DataInoputSchema will have this instead nil:
 		// 	&{Schema:{Type:0 StringValue: IntValue:0 FloatValue:0 MapValue:map[] SliceValue:[] BoolValue:false}
 		// We can, make Schema pointer, or, find a way to make all fields from Object as pointer.
 		// Using Schema: FromNull does have the same effect than just not set it.
-		//{
```
Comment (ricardozanini) [inline model/workflow_validator_test.go]: I think we can remove this comment?

**Review by ricardozanini — APPROVED** [review]

File: model/workflow_validator_test.go (hunk 2 above)
Comment (spolti) [reply model/workflow_validator_test.go]: +1 :)

**Comment by ricardozanini** [comment]
@ribeiromiranda wanna take a look?

File: model/workflow.go [hunk 3]
```diff
@@ -515,7 +517,14 @@ type dataInputSchemaUnmarshal DataInputSchema
 // UnmarshalJSON implements json.Unmarshaler
 func (d *DataInputSchema) UnmarshalJSON(data []byte) error {
 	d.ApplyDefault()
-	return util.UnmarshalPrimitiveOrObject("dataInputSchema", data, &d.Schema, (*dataInputSchemaUnmarshal)(d))
+	if data[0] == '"' && len(data) > 0 {
```
Comment (ribeiromiranda) [inline model/workflow.go:520]: @spolti @ricardozanini 

You can change `UnmarshalJSON`. Because according to the specification, when it is `string` it loads the json schema from external resource.

```go
func (d *DataInputSchema) UnmarshalJSON(data []byte) error {
       err := util.UnmarshalObject("dataInputSchema", data, (*dataInputSchemaUnmarshal)(d))
       if err != nil {
               return err
       }

       if d.Schema.Type == String {
               data, err := util.LoadExternalResource(d.Schema.StringValue)
               if err != nil {
                       return err
               }
               return util.UnmarshalObject("schema", data, d.Schema)
        }
}
```

Also change the tests when `string` to something like `file://testdata/datainputschema.json`

Obs.: The `Object struct` implements the `UnmarshalJSON`

File: parser/parser_test.go [hunk 4]
```diff
@@ -582,8 +583,21 @@ func TestFromFile(t *testing.T) {
 		}, {
 			"./testdata/workflows/dataInputSchemaValidation.yaml", func(t *testing.T, w *model.Workflow) {
 				assert.NotNil(t, w.DataInputSchema)
-
-				assert.Equal(t, "sample schema", w.DataInputSchema.Schema)
+				expected := model.FromString("sample schema")
```
Comment (ribeiromiranda) [inline parser/parser_test.go:586]: Add a test to load a external resource. Ex.: `file://testdata/datainputschema.json`

File: model/workflow_test.go [hunk 5]
```diff
@@ -496,6 +496,9 @@ func TestTransitionUnmarshalJSON(t *testing.T) {
 }
 
 func TestDataInputSchemaUnmarshalJSON(t *testing.T) {
+
+	schemaName := FromString("schema name")
```
Comment (ribeiromiranda) [inline model/workflow_test.go:500]: Change the test to a json schema `Object`

**Review by ribeiromiranda — CHANGES_REQUESTED** [review]

**Comment by ricardozanini** [comment]
@spolti can you rebase and review @ribeiromiranda's comment?

**Comment by ricardozanini** [comment]
@spolti are you still on this? :D

**Comment by spolti** [comment]
Yes, sry, will try to revisit it this or next week.

**Comment by spolti** [comment]
@ribeiromiranda hi, 
Just got it using your tool, the version in the go.mod does not looks correct.
https://github.com/galgotech/builder-gen/blob/main/go.mod#L3C1-L3C11?

```bash
go: github.com/galgotech/builder-gen@latest (in github.com/galgotech/builder-gen@v0.0.0-20231121195112-e44977c5b75f): go.mod:3: invalid go version '1.20.11': must match format 1.23
```

File: Makefile [hunk 6]
```diff
@@ -14,7 +14,9 @@ lint:
 
 .PHONY: test
 coverage="false"
-test: deepcopy buildergen
+# temporary disable buildergen due
+# in github.com/galgotech/builder-gen@v0.0.0-20231121195112-e44977c5b75f): go.mod:3: invalid go version '1.20.11': must match format 1.23
```
Comment (spolti) [inline Makefile:18]: Once it is fixed we can revert this change back.

File: model/workflow_test.go (hunk 5 above)
Comment (spolti) [reply model/workflow_test.go:502]: seems that it is not needed.

**Comment by spolti** [comment]
There is a small issue on a third party lib, please take a look in the comments.

**Review by ricardozanini — COMMENTED** [review]
@ribeiromiranda can you downgrade your library's Go version?

File: Makefile (hunk 6 above)
Comment (ribeiromiranda) [reply Makefile:18]: Changed version to 1.19.

If necessary, change `hack/builder-gen.sh`
```patch
diff --git a/hack/builder-gen.sh b/hack/builder-gen.sh
index 083b187..c79a270 100755
--- a/hack/builder-gen.sh
+++ b/hack/builder-gen.sh
@@ -32,7 +32,7 @@ shift 1
   # make sure your GOPATH env is properly set.
   # it will go under $GOPATH/bin
   cd "$(dirname "${0}")"
-  GO111MODULE=on go install github.com/galgotech/builder-gen@latest
+  GO111MODULE=on go install github.com/galgotech/builder-gen@v0.0.1
 )
```

**Comment by ribeiromiranda** [comment]
> There is a small issue on a third party lib, please take a look in the comments.

Changed version to 1.19

**Comment by spolti** [comment]
updated. Thanks @ribeiromiranda

**Comment by ribeiromiranda** [comment]
@ricardozanini @spolti Are all inputs possible?

1.
```yaml
id: Valid DataInputSchema
version: '1.0'
specVersion: '0.8'
start: Start
dataInputSchema: "file://testdata/datainputschema.json"
...
```
2.
```yaml
id: Valid DataInputSchema
version: '1.0'
specVersion: '0.8'
start: Start
dataInputSchema: "{}"
...
```
3.
```yaml
id: Valid DataInputSchema
version: '1.0'
specVersion: '0.8'
start: Start
dataInputSchema:
  schema: "file://testdata/datainputschema.json"
...
```
4.
```yaml
id: Valid DataInputSchema
version: '1.0'
specVersion: '0.8'
start: Start
dataInputSchema:
  schema: "{}"
...
```

**Comment by ricardozanini** [comment]
@ribeiromiranda yes, it should.

**Comment by spolti** [comment]
are we clear to merge this one?

**Comment by ribeiromiranda** [comment]
@ricardozanini @spolti 
Another question, it wasn't clear to me in the specification.

Which is right, JSON with or without quotes?

```
1.
```yaml
id: Valid DataInputSchema
version: '1.0'
specVersion: '0.8'
start: Start
dataInputSchema: "{ \"test\": \"value\" }"
...
```

```
2.
```yaml
id: Valid DataInputSchema
version: '1.0'
specVersion: '0.8'
start: Start
dataInputSchema: {
  "test": "value"
}
...
```

**Comment by ribeiromiranda** [comment]
@spolti With the patch all cases below will work.
```
dataInputSchema: "{\"key\": \"value\"}"
dataInputSchema: {"key": "value"}
dataInputSchema: "file://..."
dataInputSchema:
  schema: "{\"key\": \"value\"}", "failOnValidationErrors": true }
dataInputSchema:
  schema: {"key": "value"}, "failOnValidationErrors": true }
dataInputSchema:
  schema: "file://...", "failOnValidationErrors": true }
```

```patch
diff --git a/model/workflow.go b/model/workflow.go
index d0ac4c7..aa72d1f 100644
--- a/model/workflow.go
+++ b/model/workflow.go
@@ -15,8 +15,9 @@
 package model
 
 import (
+	"bytes"
 	"encoding/json"
-	"regexp"
+	"errors"
 
 	"github.com/serverlessworkflow/sdk-go/v2/util"
 )
@@ -522,33 +523,41 @@ type dataInputSchemaUnmarshal DataInputSchema
 // UnmarshalJSON implements json.Unmarshaler
 func (d *DataInputSchema) UnmarshalJSON(data []byte) error {
 	d.ApplyDefault()
-	err := util.UnmarshalObject("dataInputSchema", data, (*dataInputSchemaUnmarshal)(d))
+
+	// expected: data = "{\"key\": \"value\"}"
+	//           data = {"key": "value"}
+	//	         data = "file://..."
+	//           data = { "schema": "{\"key\": \"value\"}", "failOnValidationErrors": true }
+	//           data = { "schema": {"key": "value"}, "failOnValidationErrors": true }
+	//           data = { "schema": "file://...", "failOnValidationErrors": true }
+
+	schemaString := ""
+	err := util.UnmarshalPrimitiveOrObject("dataInputSchema", data, &schemaString, (*dataInputSchemaUnmarshal)(d))
 	if err != nil {
 		return err
 	}
 
-	if d.Schema != nil && d.Schema.Type == String {
-		// Define the regex pattern to match the prefixes
-		pattern := `^(http|https|file)`
-		regex := regexp.MustCompile(pattern)
-		// if it is not external, treat as JSON object
-		if !regex.MatchString(d.Schema.StringValue) {
-			point := FromString(d.Schema.StringValue)
-			d.Schema = &point
+	if d.Schema != nil {
+		if d.Schema.Type == Map {
 			return nil
-		}
 
-		data, err := util.LoadExternalResource(d.Schema.StringValue)
-		if err != nil {
-			return err
+		} else if d.Schema.Type == String {
+			schemaString = d.Schema.StringValue
+
+		} else {
+			return errors.New("invalid dataInputSchema must be a string or object")
 		}
+	}
 
-		er := util.UnmarshalObject("schema", data, &d.Schema)
-		// clean the string value to avoid the json URI being appended
-		d.Schema.StringValue = ""
-		return er
+	if schemaString != "" {
+		data = []byte(schemaString)
+		if bytes.TrimSpace(data)[0] != '{' {
+			data = []byte("\"" + schemaString + "\"")
+		}
 	}
-	return nil
+
+	d.Schema = new(Object)
+	return util.UnmarshalObjectOrFile("schema", data, &d.Schema)
 }
 
 // ApplyDefault set the default values for Data Input Schema
diff --git a/model/workflow_test.go b/model/workflow_test.go
index 70aa2d8..a5aa42a 100644
--- a/model/workflow_test.go
+++ b/model/workflow_test.go
@@ -499,7 +499,11 @@ func TestTransitionUnmarshalJSON(t *testing.T) {
 
 func TestDataInputSchemaUnmarshalJSON(t *testing.T) {
 
-	schemaName := FromString("schema name")
+	var schemaName Object
+	err := json.Unmarshal([]byte("{\"key\": \"value\"}"), &schemaName)
+	if !assert.NoError(t, err) {
+		return
+	}
 
 	type testCase struct {
 		desp   string
@@ -511,16 +515,25 @@ func TestDataInputSchemaUnmarshalJSON(t *testing.T) {
 	testCases := []testCase{
 		{
 			desp: "string success",
-			data: `"schema name"`,
+			data: "{\"key\": \"value\"}",
 			expect: DataInputSchema{
 				Schema:                 &schemaName,
 				FailOnValidationErrors: true,
 			},
-			err: `dataInputSchema must be string or object`,
+			err: ``,
 		},
 		{
-			desp: `object success`,
-			data: `{"schema": "schema name"}`,
+			desp: "string fail",
+			data: "{\"key\": }",
+			expect: DataInputSchema{
+				Schema:                 &schemaName,
+				FailOnValidationErrors: true,
+			},
+			err: `invalid character '}' looking for beginning of value`,
+		},
+		{
+			desp: `object success (without quotes)`,
+			data: `{"key": "value"}`,
 			expect: DataInputSchema{
 				Schema:                 &schemaName,
 				FailOnValidationErrors: true,
@@ -528,22 +541,32 @@ func TestDataInputSchemaUnmarshalJSON(t *testing.T) {
 			err: ``,
 		},
 		{
-			desp: `object fail`,
-			data: `{"schema": "schema name}`,
+			desp: `schema object success`,
+			data: `{"schema": "{\"key\": \"value\"}"}`,
 			expect: DataInputSchema{
 				Schema:                 &schemaName,
 				FailOnValidationErrors: true,
 			},
-			err: `unexpected end of JSON input`,
+			err: ``,
 		},
 		{
-			desp: `object key invalid`,
-			data: `{"schema_invalid": "schema name"}`,
+			desp: `schema object success (without quotes)`,
+			data: `{"schema": {"key": "value"}}`,
 			expect: DataInputSchema{
+				Schema:                 &schemaName,
 				FailOnValidationErrors: true,
 			},
 			err: ``,
 		},
+		{
+			desp: `schema object fail`,
+			data: `{"schema": "schema name}`,
+			expect: DataInputSchema{
+				Schema:                 &schemaName,
+				FailOnValidationErrors: true,
+			},
+			err: `unexpected end of JSON input`,
+		},
 	}
 	for _, tc := range testCases {
 		t.Run(tc.desp, func(t *testing.T) {
@@ -551,13 +574,14 @@ func TestDataInputSchemaUnmarshalJSON(t *testing.T) {
 			err := json.Unmarshal([]byte(tc.data), &v)
 
 			if tc.err != "" {
-				assert.Error(t, err)
-				assert.Regexp(t, tc.err, err)
+				assert.Error(t, err, tc.desp)
+				assert.Regexp(t, tc.err, err, tc.desp)
 				return
 			}
 
-			assert.NoError(t, err)
-			assert.Equal(t, tc.expect, v)
+			assert.NoError(t, err, tc.desp)
+			assert.Equal(t, tc.expect.Schema, v.Schema, tc.desp)
+			assert.Equal(t, tc.expect.FailOnValidationErrors, v.FailOnValidationErrors, tc.desp)
 		})
 	}
 }
diff --git a/util/unmarshal.go b/util/unmarshal.go
index 9d5b1c2..d00e9d2 100644
--- a/util/unmarshal.go
+++ b/util/unmarshal.go
@@ -221,7 +221,7 @@ func UnmarshalObjectOrFile[U any](parameterName string, data []byte, valObject *
 	}
 
 	data = bytes.TrimSpace(data)
-	if data[0] == '{' && parameterName != "constants" && parameterName != "timeouts" {
+	if data[0] == '{' && parameterName != "constants" && parameterName != "timeouts" && parameterName != "schema" {
 		extractData := map[string]json.RawMessage{}
 		err = json.Unmarshal(data, &extractData)
 		if err != nil {
```

**Comment by ricardozanini** [comment]
> @ricardozanini @spolti Another question, it wasn't clear to me in the specification.
> 
> Which is right, JSON with or without quotes?
> 
> ```
> 1.
> ```yaml
> id: Valid DataInputSchema
> version: '1.0'
> specVersion: '0.8'
> start: Start
> dataInputSchema: "{ \"test\": \"value\" }"
> ...
> ```
> 
> ```
> 2.
> ```yaml
> id: Valid DataInputSchema
> version: '1.0'
> specVersion: '0.8'
> start: Start
> dataInputSchema: {
>   "test": "value"
> }
> ...
> ```

If we can convert the `{ "test": "value" }` into a valid JSON Schema, both are.

**Comment by ricardozanini** [comment]
@spolti can you apply @ribeiromiranda's patch?

**Comment by spolti** [comment]
Done.

Thanks @ribeiromiranda

**Comment by spolti** [comment]
Codecov is complaining about rate limit:
`Rate limit reached. Please upload with the Codecov repository upload token to resolve issue.`

**Comment by ricardozanini** [comment]
@spolti I'll merge and solve this issue later.
